name: Run makeInstall.sh on macOS 13

on:
  workflow_dispatch:
  push:
    branches: ["**"]     # Run on push to any branch
  pull_request:
    branches: ["**"]     # Run on PR to any branch

jobs:
  run-make-install:
    runs-on: macos-13  # Specify macOS version 13
    steps:

      # Rust
      - name: Set up Rust
        id: set-up-rust
        uses: moonrepo/setup-rust@v1

      # Homebrew for OpenSSL for OPENSSL_STATIC=yes with cargo (rust)
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main

      # OpenSSL for build environment
      - name: Set up OpenSSL
        id: set-up-openssl
        run: brew install openssl

      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Grant execute permissions for the shell and bash scripts
      - name: Make scripts executable
        run: |
          chmod +x ./macos/scripts/app_setup.zsh
          chmod +x ./macos/scripts/clone.zsh
          chmod +x ./macos/scripts/build_clients.zsh
          chmod +x ./macos/install/build_server_bundle_zip.zsh
          chmod +x ./macos/install/makeAllInstalls.sh

      - name: Run app_setup.zsh
        working-directory: ./macos/scripts
        run: ./app_setup.zsh

      - name: Run clone.zsh
        working-directory: ./macos/scripts
        run: ./clone.zsh

      - name: Run build_clients.zsh
        working-directory: ./macos/scripts
        run: ./build_clients.zsh

      - name: Run build_server_bundle_zip.zsh
        working-directory: ./macos/install
        run: ./build_server_bundle_zip.zsh

      - name: get zip for terminal names
        run: |
          echo "Zip for terminal name:"
          ls -als ./releases/macos/*.zip
          cd ./releases/macos
          echo "ZIP_NAME=$(ls *.pkg | head -n 1)" >> $GITHUB_ENV
          cd ../..

      - name: Upload zip for terminal artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ZIP_NAME }}
          path: ./releases/macos/${{ env.ZIP_NAME }}

      - name: Run makeAllInstalls.sh
        working-directory: ./macos/install
        run: ./makeAllInstalls.sh

      - name: get Installer names
        run: |
          echo "Arm install:"
          ls -als ./macos/release/arm64/*.pkg
          cd ./macos/release/arm64
          echo "PKG_NAME_ARM=$(ls *.pkg | head -n 1)" >> $GITHUB_ENV
          cd ../../..
          
          echo "Intel install:"
          ls -als ./macos/release/intel64/*.pkg
          cd ./macos/release/intel64
          echo "PKG_NAME_INTEL=$(ls *.pkg | head -n 1)" >> $GITHUB_ENV
          cd ../../..
      - name: Upload arm64 artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PKG_NAME_ARM }}
          path: ./macos/release/arm64/${{ env.PKG_NAME_ARM }}

      - name: Upload intel64 artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PKG_NAME_INTEL }}
          path: ./macos/release/intel64/${{ env.PKG_NAME_INTEL }}
